CREATE TABLE `employment_electronic_contracts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`token` varchar(64) NOT NULL,
	`restaurantId` int NOT NULL,
	`employeeId` int,
	`employeeName` varchar(100) NOT NULL,
	`employeePhone` varchar(30),
	`employeeBirthdate` varchar(10),
	`employeeAddress` text,
	`position` varchar(50) NOT NULL DEFAULT '직원',
	`contractType` enum('permanent','fixed_term','part_time','daily') NOT NULL DEFAULT 'part_time',
	`contractStart` date NOT NULL,
	`contractEnd` date,
	`hasProbation` boolean NOT NULL DEFAULT false,
	`probationMonths` int DEFAULT 0,
	`workPlace` varchar(200),
	`jobDescription` text,
	`wageType` enum('hourly','monthly') NOT NULL DEFAULT 'hourly',
	`wageAmount` decimal(12,2) NOT NULL,
	`weeklyHours` decimal(5,2) NOT NULL DEFAULT '40',
	`workStartTime` varchar(5) DEFAULT '09:00',
	`workEndTime` varchar(5) DEFAULT '18:00',
	`breakMinutes` int DEFAULT 60,
	`weeklyHoliday` varchar(20) DEFAULT '일요일',
	`payDay` int DEFAULT 25,
	`payMethod` enum('bank_transfer','cash') DEFAULT 'bank_transfer',
	`mealProvided` boolean NOT NULL DEFAULT false,
	`mealAllowance` decimal(10,2) DEFAULT '0',
	`socialInsurance` boolean NOT NULL DEFAULT true,
	`over5Employees` boolean NOT NULL DEFAULT false,
	`nightShiftConsent` boolean NOT NULL DEFAULT false,
	`specialTerms` text,
	`status` enum('draft','sent','signed','expired','cancelled') NOT NULL DEFAULT 'draft',
	`sentAt` timestamp,
	`signedAt` timestamp,
	`employeeSignature` text,
	`signedIp` varchar(45),
	`createdBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `employment_electronic_contracts_id` PRIMARY KEY(`id`),
	CONSTRAINT `employment_electronic_contracts_token_unique` UNIQUE(`token`)
);
